### ISSUE TITLE
Dataset cannot be found 

### ISSUE THREAD

**Issue by amindadgar** [zeynepCankara/clothing_detector#3]
Hi, I was trying to use this project as a part of my university project. Unfortunately, I can't find the dataset. Can you help me with that?

I have a really limited time, I would really appreciate it if you can help me ASAP.

**Comment by tjay27** [comment]
Hi, I mailed the people who made it and they said it is no longer available.

**Comment by amindadgar** [comment]
> Hi, I mailed the people who made it and they said it is no longer available.

Oh ok, Thanks for your response, So I'm closing this issue.
